// <auto-generated />
using System;
using BlazorCRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorCRUD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220511151345_RemoveCountryUpdateCity")]
    partial class RemoveCountryUpdateCity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorCRUD.Data.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("BlazorCRUD.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "USA"
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "India"
                        });
                });

            modelBuilder.Entity("BlazorCRUD.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BlazorCRUD.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is sample content for Post 1.",
                            Title = "Post 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is sample content for Post 2.",
                            Title = "Post 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "This is sample content for Post 3.",
                            Title = "Post 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "This is sample content for Post 4.",
                            Title = "Post 4"
                        },
                        new
                        {
                            Id = 5,
                            Content = "This is sample content for Post 5.",
                            Title = "Post 5"
                        },
                        new
                        {
                            Id = 6,
                            Content = "This is sample content for Post 6.",
                            Title = "Post 6"
                        },
                        new
                        {
                            Id = 7,
                            Content = "This is sample content for Post 7.",
                            Title = "Post 7"
                        },
                        new
                        {
                            Id = 8,
                            Content = "This is sample content for Post 8.",
                            Title = "Post 8"
                        },
                        new
                        {
                            Id = 9,
                            Content = "This is sample content for Post 9.",
                            Title = "Post 9"
                        },
                        new
                        {
                            Id = 10,
                            Content = "This is sample content for Post 10.",
                            Title = "Post 10"
                        });
                });

            modelBuilder.Entity("BlazorCRUD.Data.City", b =>
                {
                    b.HasOne("BlazorCRUD.Data.Country", null)
                        .WithMany("Cities")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("BlazorCRUD.Data.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
